---
kind: ConfigMap
apiVersion: v1
metadata:
  name: st2
data:
  ST2_USER: admin
  ST2_PASSWORD: changeme
  ST2_AUTH_URL: http://st2auth:9100/
  ST2_API_URL: http://st2api:9101/
  ST2_STREAM_URL: http://st2stream:9102/
  ST2_MISTRAL_API_URL: http://mistral-api:8989/v2

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: st2-externals
data:
  ST2_MONGODB_URL: mongodb://mongo:27017/
  ST2_RABBITMQ_URL: amqp://admin:9jS+w1u07NbHtZke1m+jW4Cj@rabbitmq:5672/
  ST2_COORDINATION_BACKEND_URL: redis://:@redis:6379/
  ST2MISTRAL_RABBITMQ_URL: rabbit://admin:9jS+w1u07NbHtZke1m+jW4Cj@rabbitmq:5672/
  ST2MISTRAL_DB_URL: postgresql+psycopg2://mistral-user:2PehgWO824hcUCUMNbaVwDMT@postgres:5432/mistral

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: 9jS+w1u07NbHtZke1m+jW4Cj

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres
data:
  POSTGRES_USER: mistral-user
  POSTGRES_PASSWORD: 2PehgWO824hcUCUMNbaVwDMT
  POSTGRES_DB: mistral
