---
kind: ConfigMap
apiVersion: v1
metadata:
  name: st2
data:
  ST2_USER: admin
  ST2_PASSWORD: changeme
  ST2_AUTH_URL: http://st2auth:9100/
  ST2_API_URL: http://st2api:9101/
  ST2_STREAM_URL: http://st2stream:9102/
  ST2_MISTRAL_API_URL: http://mistral-api:8989/v2

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: st2-externals
data:
  ST2_MONGODB_URL: mongodb://st2-mongodb-mongodb-replicaset-0.st2-mongodb-mongodb-replicaset:27017,st2-mongodb-mongodb-replicaset-1.st2-mongodb-mongodb-replicaset:27017,st2-mongodb-mongodb-replicaset-2.st2-mongodb-mongodb-replicaset:27017/st2?replicaSet=rs0
  ST2_RABBITMQ_URL: amqp://st2:changeme@st2-rabbitmq-rabbitmq-ha:5672/
  ST2_COORDINATION_BACKEND_URL: redis://:@your.redis.cache.amazonaws.com:6379/
  ST2MISTRAL_RABBITMQ_URL: rabbit://st2:changeme@st2-rabbitmq-rabbitmq-ha:5672/
  ST2MISTRAL_DB_URL: postgresql+psycopg2://st2:changeme@your.cluster.us-west-2.rds.amazonaws.com:5432/st2_mistral
