dependencies:
- name: mongodb
  version: 0.4.25
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq
  version: 0.6.15
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: postgresql
  version: 0.8.7
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 1.1.8
  repository: https://kubernetes-charts.storage.googleapis.com/
